language: emacs-lisp
sudo: false
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=snapshot
matrix:
  allow_failures:
    - env: EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - curl -fSOL https://github.com/flycheck/emacs-travis/raw/master/emacs-travis.mk
  - make -f emacs-travis.mk install_emacs install_cask
script:
  - make compile
